// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ID struct {
	ID string `json:"id"`
}

type InputID struct {
	ID string `json:"id"`
}

type NewUser struct {
	Name  string `json:"name"`
	Place string `json:"place"`
}

type Status struct {
	Status int `json:"status"`
}

type UpdatedUser struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Place string `json:"place"`
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Place string `json:"place"`
}
